segmentio/analytics-android

analytics-core/src/main/java/com/segment/analytics/Analytics.java, analytics-core/src/test/java/com/segment/analytics/AnalyticsTest.java
=> Rename skipBundledIntegrations to disableBundledIntegrations

analytics-core/build.gradle, analytics-core/gradle.properties, analytics-integrations/amplitude/gradle.properties, analytics-integrations/appsflyer/gradle.properties, analytics-integrations/bugsnag/gradle.properties, analytics-integrations/countly/gradle.properties, analytics-integrations/crittercism/gradle.properties, analytics-integrations/flurry/gradle.properties, analytics-integrations/kahuna/gradle.properties, analytics-integrations/leanplum/gradle.properties, analytics-integrations/localytics/gradle.properties, analytics-integrations/mixpanel/gradle.properties, analytics-integrations/quantcast/gradle.properties, analytics-integrations/tapstream/gradle.properties, analytics-wear/build.gradle, analytics-wear/gradle.properties, gradle/integration.gradle
=> Declare AAR packaging for integrations

analytics-integrations/mixpanel/src/main/java/com/segment/analytics/internal/integrations/MixpanelIntegration.java, analytics-integrations/mixpanel/src/test/java/com/segment/analytics/internal/integrations/MixpanelTest.java
This edit changes the addSpecialProperties method to addSuperProperties to match both the [Mixpanel documentation]() and our iOS SDK.
=> Changing Mixpanel SpecialProperties to SuperProperties closes #240

analytics-integrations/amplitude/build.gradle
Fails with https://cloudup.com/cXg-JbqMDTK
=> Update Amplitude SDK

analytics-integrations/crittercism/build.gradle, analytics-integrations/crittercism/src/main/java/com/segment/analytics/internal/integrations/CrittercismIntegration.java, analytics-integrations/crittercism/src/test/java/com/segment/analytics/internal/integrations/CrittercismTest.java
1. Update SDK to 5.0.6
2. Add settings to disable service monitoring and set custom version
name
=> Update Crittercism Integration

analytics-integrations/google-analytics/src/main/java/com/segment/analytics/internal/integrations/GoogleAnalyticsIntegration.java
Swapped the order of googleAnalyticsInstance and tracker initialization to avoid the NPE.
Closes #265
=> Fix NPE on googleAnalyticsInstance.newTracker(...)

analytics-integrations/localytics/src/main/java/com/segment/analytics/internal/integrations/LocalyticsIntegration.java, analytics-integrations/localytics/src/test/java/com/segment/analytics/internal/integrations/LocalyticsTest.java
@f2prateek could you review this? Adds custom dimensions functionality as described here: https://trello.com/c/lW9i23fC. Could you take a stab on iOS? There's a couple other things on iOS on that ticket.
=> Localytics: added support for custom dimensions

analytics-integrations/moengage/build.gradle
Updates the MoEngage SDK to 5.2.21
=> Updating MoEngage SDK

analytics-core/src/main/java/com/segment/analytics/SegmentDispatcher.java
=> Dump QueueFile info if we detect an ArrayIndexOutOfBoundsExcpetion

analytics-integrations/moengage/build.gradle
=> Update SDK version

analytics-integrations/amplitude/build.gradle
Few bug fixes: https://github.com/amplitude/Amplitude-Android/releases
=> Updating Amplitude SDK to v2.0.4

analytics-core/src/main/java/com/segment/analytics/Properties.java, analytics-integrations/google-analytics/src/main/java/com/segment/analytics/internal/integrations/GoogleAnalyticsIntegration.java
=> Update GA integration

analytics-core-tests/src/test/java/com/segment/analytics/AnalyticsTest.java, analytics-core-tests/src/test/java/com/segment/analytics/IntegrationManagerTest.java, analytics-core-tests/src/test/java/com/segment/analytics/SegmentDispatcherTest.java, analytics-core-tests/src/test/java/com/segment/analytics/internal/LogTest.java, analytics-core-tests/src/test/java/com/segment/analytics/internal/UtilsTest.java, analytics-core/src/main/java/com/segment/analytics/Analytics.java, analytics-core/src/main/java/com/segment/analytics/IntegrationManager.java, analytics-core/src/main/java/com/segment/analytics/SegmentDispatcher.java, analytics-core/src/main/java/com/segment/analytics/internal/Log.java, analytics-core/src/main/java/com/segment/analytics/internal/Utils.java, analytics-integrations/amplitude/src/main/java/com/segment/analytics/internal/integrations/AmplitudeIntegration.java, analytics-integrations/amplitude/src/test/java/com/segment/analytics/internal/integrations/AmplitudeTest.java, analytics-integrations/appsflyer/src/main/java/com/segment/analytics/internal/integrations/AppsFlyerIntegration.java, analytics-integrations/appsflyer/src/test/java/com/segment/analytics/internal/integrations/AppsFlyerTest.java, analytics-integrations/kahuna/src/main/java/com/segment/analytics/internal/integrations/KahunaIntegration.java, analytics-integrations/kahuna/src/test/java/com/segment/analytics/internal/integrations/KahunaTest.java, analytics-integrations/mixpanel/src/main/java/com/segment/analytics/internal/integrations/MixpanelIntegration.java, analytics-integrations/mixpanel/src/test/java/com/segment/analytics/internal/integrations/MixpanelTest.java, analytics-samples/analytics-sample/src/main/java/com/segment/analytics/sample/SampleApp.java, analytics-wear/src/main/java/com/segment/analytics/PhoneAnalyticsListenerService.java
Adds a verbose log level for integrations.
=> New Logging API for integrations

analytics-integrations/moengage/build.gradle, analytics-integrations/moengage/src/main/java/com/segment/analytics/internal/integrations/MoEngageIntegration.java, analytics-integrations/moengage/src/test/java/com/segment/analytics/internal/integrations/MoEngageTest.java
Bump SDK version and integration changes
=> MoEngage SDK updates

analytics-integrations/amplitude/build.gradle
Minor update with a bunch of small fixes: https://github.com/amplitude/Amplitude-Android/releases/tag/v2.2.0
=> updating Amplitude android SDK to v2.2.0

analytics-integrations/moengage/build.gradle
=> Upgrading to MoEngage 5.3.12

analytics/src/main/java/com/segment/analytics/Analytics.java
=> Fix possible NPE when device is offline.

analytics/src/main/java/com/segment/analytics/Analytics.java
In backup mode, we enable just the Segment integration, but we don't
save it to the disk cache so that on the next run we can still ask for
an update from the server.
This causes the disk cache to return null when running an operation,
throwing a NPE for track events.
The fix is to keep an extra variable just for the project settings in
use, and the cache is only used to save the settings, or retrieve from
it during initialization.
Closes #400.
=> Don't use cache when forwarding events.

analytics/src/main/java/com/segment/analytics/AnalyticsContext.java
=> Check for AdvertisingIdClient instead of Analytics

analytics-tests/src/test/java/com/segment/analytics/ValueMapTest.java, analytics/src/main/java/com/segment/analytics/SegmentIntegration.java
=> Dont mutate original paylaod

analytics-tests/src/test/java/com/segment/analytics/AnalyticsTest.java
=> add test case for registering activity lifecycle callbacks

analytics-tests/src/test/java/com/segment/analytics/SegmentIntegrationTest.java, analytics/src/main/java/com/segment/analytics/SegmentIntegration.java
=> Remove Segment.io:false in payload

analytics-tests/src/test/java/com/segment/analytics/AnalyticsTest.java, analytics/src/main/java/com/segment/analytics/Analytics.java, analytics/src/main/java/com/segment/analytics/BooleanPreference.java
=> Add Opt Out method

analytics/src/main/java/com/segment/analytics/PayloadQueue.java
=> Guard against ArrayIndexOutOfBoundsException

CHANGELOG.md, analytics/src/main/java/com/segment/analytics/ConnectionFactory.java, gradle.properties
@tonyxiao  @f2prateek  Updates cdn hostname from `cdn.segment.com` to `cdn-settings.segment.com`. Tony made me push the release commit in the same PR. 🚌
=> Hotfix version 4.2.3 - update cdn hostname

analytics/src/main/java/com/segment/analytics/Analytics.java, analytics/src/main/java/com/segment/analytics/RealMiddlewareChain.java, analytics/src/main/java/com/segment/analytics/internal/Utils.java
=> Ensure that an empty list is created when no middlewares are present

analytics/src/main/java/com/segment/analytics/Analytics.java, analytics/src/test/java/com/segment/analytics/AnalyticsTest.java
This ensures that no lifecycle callbacks are queued on a executor that
has been shutdown.
Closes #523
=> Unregister ActivityLifecycleCallbacks on shutdown.

gradle/android.gradle
=> Enable text report for lint.

build.gradle, circle.yml
This also updates the supportAnnotations dependency to match the SDK versions.
=> Update for Android SDK version 26. 

analytics-samples/analytics-sample/src/androidTest/java/com/segment/analytics/E2ETest.java
Instead of adding an `if (BuildConfig.RUN_E2E_TESTS)` check in each test method, moving this logic into a rule that gets applied for all end to end tests.
The advantage isn't immediately obvious here yet, but I'm adding more tests/cases to this, and this will be useful to avoid copy pasting the code into each method.
=> Use a rule to ignore end to end tests.

analytics-samples/analytics-sample/src/main/AndroidManifest.xml, build.gradle, gradle/wrapper/gradle-wrapper.properties
Updates the following components:
* Android build plugin to 3.1.2
* Android build tool to 27.0.3
* Gradle to 4.4
=> Tooling Updates

.circleci/config.yml
Disable until LIB-695 is fixed
=> Disable Slack notifications on failed e2e tests

CHANGELOG.md, analytics-samples/analytics-sample/src/androidTest/java/com/segment/analytics/E2ETest.java, gradle.properties
Prepare for release 4.5.0-beta.0
=> Prepare for release 4.5.0-beta.0

gradle/android.gradle
Caused by https://support.sonatype.com/hc/en-us/articles/360041287334
=> Fix Roboelectric resolution

analytics/src/main/java/com/segment/analytics/AnalyticsContext.java
https://segment.atlassian.net/browse/LIB-1540
=> NFC: add documentation wrt traits and threading

analytics/src/main/java/com/segment/analytics/Analytics.java
I was able to repro the bug with and without the fix by using this patch https://gist.github.com/aultimus/2be2c165ee065107ae6d90687ca818b3
I set a breakpoint here https://github.com/segmentio/analytics-android/blob/f0d6d37a762b2811afb14460d1b8a47fd3a887fe/analytics/src/main/java/com/segment/analytics/Analytics.java#L347
launched the sample app, and confirmed that the breakpoint was hit on master, and was not hit on the fix_application_installed_events branch
=> LIB-1578: preserve BUILD and VERSION keys on reset() calls

CHANGELOG.md, analytics/src/main/java/com/segment/analytics/Analytics.java
This issue is logged here:
https://github.com/segmentio/analytics-android/issues/592
=> Bug Fix: Fix integration settings crash

.circleci/config.yml
this should fix the CI on master 🤞
=> add snyk context for e2e test

analytics-samples/analytics-sample/src/main/java/com/segment/analytics/sample/SampleApp.java
This reverts the changes on SampleApp.java while making the 4.8.0 release
=> Revert Dev changes on Sample App

.circleci/config.yml
Temporary fix until I get a concrete solution
=> Fix CI by switching build image to 28-alpha

analytics/src/test/java/com/segment/analytics/integrations/AliasPayloadTest.kt
AliasPayloadTest.java coverage:
AliasPayloadTest.kt coverage:
=> converted AliasPayloadTest to Kotlin

analytics/src/main/java/com/segment/analytics/internal/Utils.java
in order to address the issue with crashing permission check I introduced another hasPermission api that can repeat the call in case an exception has been thrown while checking the permission
Addresses this issue:
https://github.com/segmentio/analytics-android/issues/748
=> crashing permission check repeat fix

.circleci/config.yml
CircleCI is setup to build, publish snapshot and publish release on tag creation.
=> Add CircleCI config 

CHANGELOG.md, gradle.properties
* update changelog
* create tag 4.10.1
=> prepare release 4.10.1

analytics/src/main/java/com/segment/analytics/internal/Utils.java
=> fix get unique id npe

CHANGELOG.md, gradle.properties
=> prepare release 4.10.2

CHANGELOG.md, gradle.properties
* update changelog
* prepare snapshot 4.10.4
=> prepare release 4.10.3

CHANGELOG.md, gradle.properties
* prepare release 4.10.4
* prepare snapshot 4.10.5
=> prepare release 4.10.4
