segmentio/analytics-android

- analytics-integrations/amplitude/build.gradle
- gradle/android.gradle
- gradle/lint.xml
* Add PinnedAmplitudeClient to support SSL pinning.
* Deprecate static methods on Amplitude. Switch to using Amplitude.getInstance().
* Upgrade HTTP client to okhttp.
* Fix bug when initializing with user id. Api key was not set properly.
* Expose setUserProperties(JSONObject, boolean) as a static
* Handle null edge cases in location request
* Add user opt out support
* Merge user properties in setUserProperties by default
* Refactor Amplitude to be a singleton to support tests
* Add option to disable fine-grained location tracking
* Fix crash: ConcurrentModificationException in HashMap
* Fix crash: CursorWindowAllocationException in SQLite
> Update Amplitude integration to 1.5.0

- analytics-core/src/main/java/com/segment/analytics/QueueFile.java
- analytics-core/src/test/java/com/segment/analytics/QueueFileTest.java
We're seeing cases where `RandomAccessFile#write(byte[] buffer, int byteOffset, int byteCount)` is being called with a negative `byteCount`.
Ref #172.
```
java.lang.ArrayIndexOutOfBoundsException: length=4096; regionStart=0; regionLength=-1046
at java.util.Arrays.checkOffsetAndCount(Arrays.java:1719)
at libcore.io.IoBridge.write(IoBridge.java:491)
at java.io.RandomAccessFile.write(RandomAccessFile.java:688)
at com.segment.analytics.QueueFile.ringWrite(QueueFile.java:230)
at com.segment.analytics.QueueFile.ringErase(QueueFile.java:239)
at com.segment.analytics.QueueFile.remove(QueueFile.java:541)
at com.segment.analytics.Segment.performFlush(Segment.java:151)
...
```
Looking at [`int beforeEof = fileLength - position;`](https://github.com/square/tape/blob/master/tape/src/main/java/com/squar …
> Guard against negative file length in QueueFile

- analytics-core/src/main/java/com/segment/analytics/Analytics.java
The Analytics.java BundledIntegration public enum had "Leanplum" inside LOCALYTICS. This PR fixes that.
> fixing BundledIntegration Localytics closes #305

- analytics-integrations/localytics/src/main/java/com/segment/analytics/internal/integrations/LocalyticsIntegration.java
- analytics-integrations/localytics/src/test/java/com/segment/analytics/internal/integrations/LocalyticsTest.java
not sure if this is the correct way of handling just yet... but this is a first crack at adding support for customer LTV in localytics, a la: http://docs.localytics.com/index.html#Dev/Instrument/customer-ltv.html
iOS parity, for reference: https://github.com/segmentio/analytics-ios/blob/master/Analytics/Integrations/Localytics/SEGLocalyticsIntegration.m#L127-L134
> Add support for incrementing customer value in Localytics

- Makefile
- circle.yml
- gradle.properties
* Use default build tools that come installed with Circle
* Build only the release variants
I've left profiling in since it doesn't seem to have much of an impact and would be useful to keep around. https://cloudup.com/cRdTOfRFcaK
> Speed up Circle CI

- analytics-core/src/main/java/com/segment/analytics/Properties.java
- analytics-core/src/main/java/com/segment/analytics/Traits.java
- analytics-core/src/main/java/com/segment/analytics/ValueMap.java
Setting initial capacity sets the initial capacity of the delegated Map. This saves on unnecessary allocation when the map has a consistent size, which is common for tracking `Properties`.
> Adds ability to set an initial capacity for Properties

- analytics-core/src/main/java/com/segment/analytics/Analytics.java
Users are often confused by seeing crashes like #309, casued by creating
multiple instances of the analytics client with the same write key that
share the same disk queue.
This logs each time you create an analytics instance and hopefully does
a better job of surfacing incorrect uses of our API.
> Log when Analytics client is created.

- analytics-core-tests/src/test/java/com/segment/analytics/ValueMapTest.java
- analytics-core/src/main/java/com/segment/analytics/ValueMap.java
Using the JSONObject map constructor doesn't handle the case of
correctly encoding `null` values.
This PR updates it so that we iterate over the map ourselves and
correctly transform the values into their org.json representation.
Closes #224.
> Update ValueMap#toJsonObject implementation.

- analytics-core/src/main/java/com/segment/analytics/IntegrationManager.java
This fixes a race condition when the `Analytics` client is initialized
off the main thread.
1) `Analytics` is initialized on a non-main thread.
2) `registerActivityLifecycleCallbacks` is called before the thread is
created.
3) `IntegrationManager` receives onActivityPaused from the main thread,
before integrationManagerHandler is initialized.
The fix defers calling `registerActivityLifecycleCallbacks` until the
handler is initialized.
This also initializes the `SegmentIntegration` and adds it to the list
first.
Closes #329.
> Fix race condition during IntegrationManager initialization.

- analytics-core/src/main/java/com/segment/analytics/Analytics.java
- analytics-core/src/main/java/com/segment/analytics/SegmentDispatcher.java
This PR makes 2 changes:
1) Immediately shutdown the `flushScheduler` so that no more flushes are
triggered.
2) Shutdown `IntegrationManager` before shutting down the networkExecutor,
so that the `SegmentDispatcher` can be shutdown before closing the
`networkExecutor`.
> Fix shutdown implementation.

- analytics-integrations/amplitude/build.gradle
- analytics-integrations/amplitude/src/main/java/com/segment/analytics/internal/integrations/AmplitudeIntegration.java
- analytics-integrations/amplitude/src/test/java/com/segment/analytics/internal/integrations/AmplitudeTest.java
Updating Amplitude SDK to v2.0.2.
* API change - removed startSession() and endSession(). Sessions are now handled by attaching an ActivityLifecycleCallback (calling enableForeGroundTracking during init and passing in the Application). See Setup, bullet 4: https://github.com/amplitude/Amplitude-Android#setup
* Start/end session events are no longer logged by default; however, users can re-enable them by calling trackSessionEvents(true) on the Amplitude Client. This is exposed in Segment via the trackSessionEvents setting.
> Updating Amplitude SDK to v2.0.2

- analytics-core-tests/src/test/java/com/segment/analytics/AnalyticsBuilderTest.java
- analytics-core-tests/src/test/java/com/segment/analytics/AnalyticsTest.java
- analytics-core/src/main/java/com/segment/analytics/Analytics.java
This lets us fail early and warn clients taht creating multiple
analytics instances with the same writeKey/tag is an error, and can
cause problems down the line.
> Detect duplicates

- analytics-core-tests/src/test/java/com/segment/analytics/BatchPayloadWriterTest.java
- analytics-core-tests/src/test/java/com/segment/analytics/SegmentDispatcherTest.java
- analytics-core/src/main/java/com/segment/analytics/SegmentDispatcher.java
This fixes a bug that would occur when an integration was bundled and
marked with `true`. The `true` would override the bundled `false` in the
integration object of the message, and would be sent server side, as
well as client side.
This updates the code so that we merge the two and save it to disk, at
the cost of increasing our payload sizes.
Also fixes an edge case that could occur when a bundled integration was
enabled after the message got enqueued. THis way the message object
holds the truth about the integration as of the time of creation, rather
than when it gets uploaded.
> Embed integrations object into each message

- analytics-core/src/main/java/com/segment/analytics/internal/model/payloads/GroupPayload.java
- analytics-core/src/main/java/com/segment/analytics/internal/model/payloads/IdentifyPayload.java
- analytics-core/src/main/java/com/segment/analytics/internal/model/payloads/ScreenPayload.java
- analytics-core/src/main/java/com/segment/analytics/internal/model/payloads/TrackPayload.java
* TrackPayload, IdentifyPayload and ScreenPayload were missing an ending quote.
* TrackPayload and ScreenPayload didn't mark what the quoted string
represented.
* GroupPayload quoted the field and was missing an ending quote.
Closes #340
> Fix toString implementation

- analytics-core/src/main/java/com/segment/analytics/ValueMap.java
- analytics-core/src/main/java/com/segment/analytics/internal/Utils.java
- analytics-integrations/google-analytics/src/main/java/com/segment/analytics/internal/integrations/GoogleAnalyticsIntegration.java
- analytics-integrations/google-analytics/src/test/java/com/segment/analytics/internal/integrations/GoogleAnalyticsTest.java
* Add support for custom dimensions and metrics.
* Send a regular event in addition to ecommerce events for any ecommerce
calls.
* Dont set screenName to null.
* Traits/Properties are only set on if they represent special
values or are mapped by custom dimensions/metrics.
Closes #333
> Improve GA integration

- analytics-core-tests/src/test/java/com/segment/analytics/AnalyticsContextTest.java
- analytics-core/src/main/java/com/segment/analytics/Analytics.java
- analytics-core/src/main/java/com/segment/analytics/AnalyticsContext.java
- analytics-core/src/main/java/com/segment/analytics/internal/Utils.java
This PR adds an option to the `Builder`, `collectDeviceId`.
If the option is disabled, the `device:id` property of the device json object will use the `anonymousId` in place of the device identifier. This option is enabled by default.
Some terms-of-service do not allow this type of collection to take place, so it helps our adoption of Segment knowing we can disable it.
> Add 'collectDeviceId' Builder option

- analytics-integrations/amplitude/build.gradle
A bug fix and added support for user property operations: https://github.com/amplitude/Amplitude-Android/releases/tag/v2.1.0.
The underlying implementation for setUserProperties now uses our identify api, but the Segment Identify call should still work as intended.
> updating Amplitude SDK to v2.1.0

- analytics-integrations/moengage/src/main/java/com/segment/analytics/internal/integrations/MoEngageIntegration.java
- analytics-integrations/moengage/src/test/java/com/segment/analytics/internal/integrations/MoEngageTest.java
Fix for #358
Switching to JSONObject to retain datatypes for event properties. Updating the test cases accordingly.
> MoEngage Changes

- analytics-tests/src/test/java/com/segment/analytics/AnalyticsTest.java
- analytics/src/main/java/com/segment/analytics/Analytics.java
Previously we were setting `integration: true` for bundled integrations.
This would cause it to be processed client and server side. This commit
fixes the behaviour and adds a test case.
> Fix disabling bundled integrations server side.

- analytics-tests/src/test/java/com/segment/analytics/AnalyticsTest.java
- analytics-tests/src/test/java/com/segment/analytics/TestUtils.java
- analytics/src/main/java/com/segment/analytics/Analytics.java
- analytics/src/main/java/com/segment/analytics/IntegrationOperation.java
- analytics/src/main/java/com/segment/analytics/Options.java
Previously if you sent `All: false`, we'd only use the tracking plan to
figure out if the track event should be sent to integrations.
This updates is so that the Options object takes precedence over all
else. The event tracking plan cannot override options and only fill in
missing pieces.
> Refactor Options handling

- analytics/src/main/java/com/segment/analytics/AnalyticsContext.java
- analytics/src/main/java/com/segment/analytics/GetAdvertisingIdTask.java
Previously we were simply copying over isLimitAdTracking to
adTrackingEnabled. These fields are the inverse of each other, so this
commit fixes the logic and makes it so that adTrackingEnabled is
recorded as !isLimitAdTracking.
Also completely stop recording advertisingId if adTrackingEnabled is false.
> Fix logic for collecting isLimitAdTracking

- analytics-tests/src/test/java/com/segment/analytics/AnalyticsTest.java
- analytics/src/main/java/com/segment/analytics/Analytics.java
- analytics/src/main/java/com/segment/analytics/AnalyticsContext.java
- analytics/src/main/java/com/segment/analytics/GetAdvertisingIdTask.java
Retrieving the advertising ID from Play Services is asynchronous. This
means events fired before we have the advertising ID may not have this
information available.
This commit makes a few changes to deal with this. First we setup a
CountDownLatch to synchronize between the GetAdvertisindIdTask and the
enqueuing code. This has the potential to block enqueues for a while, so
we implement a 5 second timeout for waiting. The latch is released
either if play services is not available or when the task completes.
Additionally, this makes the code to fire application lifecycle events
async as well, so that we don't block initialization for too long.
> Wait for advertising ID to be populated before enqueing events.

- analytics/src/main/java/com/segment/analytics/GetAdvertisingIdTask.java
adTrackingEnabled is false).
Integrations will use `adTrackingEnabled` (which is equivalent to
`!isLimitAdTrackingEnabled`) to check if they should use this for
adTracking.
> Collect advertisingId even if isLimitAdTrackingEnabled is true (i.e.

- analytics-tests/src/test/java/com/segment/analytics/internal/UtilsTest.java
- analytics/src/main/java/com/segment/analytics/internal/Utils.java
> Fix how NullableConcurrentHashMap handles nulls in putAll method

- analytics-tests/build.gradle
- analytics-tests/src/test/java/com/segment/analytics/AnalyticsTest.java
- analytics-tests/src/test/java/com/segment/analytics/ValueMapCacheTest.java
- analytics-tests/src/test/java/com/segment/analytics/internal/UtilsTest.java
- analytics/src/main/java/com/segment/analytics/Analytics.java
- analytics/src/main/java/com/segment/analytics/ProjectSettings.java
- analytics/src/main/java/com/segment/analytics/Traits.java
- analytics/src/main/java/com/segment/analytics/ValueMap.java
- analytics/src/main/java/com/segment/analytics/internal/Utils.java
Previously (until version 4.1.6 and the upcoming 4.1.7 release) shared preferences were not namespaced by a tag.
This meant that all analytics instances shared the same shared
preferences.
Going forwards, the preferences will be namespaced, and a migration is
added to copy over old preferences.
Also fixes the reset method to blow the entire sharedPreferences object.
> Namespace SharedPreferences

- analytics/src/main/java/com/segment/analytics/Analytics.java
Previously, CDN settings would be updated on every launch instead of
every 24 hours.
> Fix Cache expiration

- analytics-tests/src/test/java/com/segment/analytics/PropertiesTest.java
- analytics/src/main/java/com/segment/analytics/Properties.java
- analytics/src/main/java/com/segment/analytics/internal/Utils.java
Previously putProducts was storing an array instead of copying the
array.
With Segment specifically this also caused issues with serialization.
```
"properties": {
"products": "[Lcom.segment.analytics.Properties$Product;@36db3d6"
}
```
> Fix Properties.putProducts()

- analytics-tests/build.gradle
- analytics-tests/src/test/java/com/segment/analytics/AnalyticsBuilderTest.java
- analytics-tests/src/test/java/com/segment/analytics/AnalyticsContextTest.java
- analytics-tests/src/test/java/com/segment/analytics/AnalyticsTest.java
- analytics-tests/src/test/java/com/segment/analytics/BatchPayloadWriterTest.java
- analytics-tests/src/test/java/com/segment/analytics/CartographerTest.java
- analytics-tests/src/test/java/com/segment/analytics/ClientTest.java
- analytics-tests/src/test/java/com/segment/analytics/CryptoTest.java
- analytics-tests/src/test/java/com/segment/analytics/LoggerTest.java
- analytics-tests/src/test/java/com/segment/analytics/OptionsTest.java
- analytics-tests/src/test/java/com/segment/analytics/ProjectSettingsTest.java
- analytics-tests/src/test/java/com/segment/analytics/SegmentIntegrationTest.java
- analytics-tests/src/test/java/com/segment/analytics/StatsTest.java
- analytics-tests/src/test/java/com/segment/analytics/TraitsTest.java
- analytics-tests/src/test/java/com/segment/analytics/ValueMapCacheTest.java
- analytics-tests/src/test/java/com/segment/analytics/ValueMapTest.java
- analytics-tests/src/test/java/com/segment/analytics/integrations/BasePayloadTest.java
- analytics-tests/src/test/java/com/segment/analytics/internal/UtilsTest.java
- build.gradle
- gradle/android.gradle
This also adds jcenter because this is where the new plugin versions are
hosted.
This also updates Robolectric, because the plugin update changes build
outputs that Robolectric relies on:
```
java.lang.RuntimeException: java.lang.RuntimeException:
build/intermediates/manifests/full/debug/AndroidManifest.xml not found
or not a file; it should point to your project's AndroidManifest.xml
```
> Update Android grade plugin

- analytics/src/main/java/com/segment/analytics/internal/Utils.java
From the docs:
https://developer.android.com/reference/java/text/SimpleDateFormat.html
```
Date formats are not synchronized. It is recommended to create
separate format instances for each thread. If multiple threads access
a format concurrently, it must be synchronized externally.
```
This is likely causing us to send invalid timestamps, as seen in some s3 buckets, e.g. `2016-12-23T00:0017:40+1300` and `2017-1-05T16:44:34+0800`.
> Wrap DateFormat in a thread local instance.

- analytics-tests/build.gradle
> Remove PowerMock dependency for testing.

- analytics/src/main/java/com/segment/analytics/Analytics.java
> Disable attribution tracking by default

- analytics/src/main/java/com/segment/analytics/Analytics.java
- analytics/src/main/java/com/segment/analytics/Client.java
- analytics/src/main/java/com/segment/analytics/internal/Utils.java
- analytics/src/test/java/com/segment/analytics/ClientTest.java
When the status code is above 300 (Don't know for sure if for all codes, but for some of them for sure), `getInputStream()` throws `FileNotFoundException` and the stream is in `getErrorStream()`.
> Fix calling to getInputStream on errors

- analytics/src/test/java/com/segment/analytics/AnalyticsContextTest.java
1. Split AnalyticsContext create test into two.
2. Only check for local key, not value because we might be running tests on non en-US locale computers.
> Test Updates

- analytics/src/main/java/com/segment/analytics/IntegrationOperation.java
- analytics/src/test/java/com/segment/analytics/IntegrationOperationTest.java
Ref: https://paper.dropbox.com/doc/Sending-Disabled-Events-evdrvByT2cYUErnrbAUa3
> Send disabled events to Segment

- analytics/src/main/java/com/segment/analytics/IntegrationOperation.java
- analytics/src/test/java/com/segment/analytics/IntegrationOperationTest.java
If an event is not present in the tracking plan, we'll now lookup the schema defaults for the project.
If the event is disabled in the schema default, it will only be sent to the Segment integration (i.e. api.segment.io).
If the event is enabled in the schema default, it will be sent to all integrations.
Ref: https://paper.dropbox.com/doc/Schema-Client-Side-Defaults-DufdS8Ej43mnFXvvMqm1b
> Support schema defaults for new events.

- analytics-samples/analytics-sample/build.gradle
- analytics-samples/analytics-wear-sample/build.gradle
- analytics-wear/build.gradle
- analytics/src/main/java/com/segment/analytics/Analytics.java
- analytics/src/main/java/com/segment/analytics/internal/Utils.java
The update in #556 added some new lint warnings. This fixes or suppresses all of them.
Full list:
```
/home/circleci/analytics-android/analytics-wear/build.gradle:9: Warning: A newer version of com.google.android.gms:play-services-wearable than 10.2.6 is available: 11.0.4 [GradleDependency]
compile 'com.google.android.gms:play-services-wearable:10.2.6'
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/circleci/analytics-android/analytics-samples/analytics-wear-sample/build.gradle:15: Warning: A newer version of com.google.android.support:wearable than 1.1.0 is available: 2.0.5 [GradleDependency]
compile 'com.google.android.support:wearable:1.1.0'
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Explanation for issues of type "GradleDependency":
This detector looks …
```
> Fix or suppress all Lint warnings

- analytics-samples/analytics-sample/build.gradle
- build.gradle
* Need to add the google repo to the buildscript since that's where the new versions are hosted.
* Butterknife change is required to fix this error:
```
> Annotation processors must be explicitly declared now.  The following dependencies on the compile classpath are found to contain annotation processor.  Please add them to the annotationProcessor configuration.
- butterknife-compiler-8.6.0.jar (com.jakewharton:butterknife-compiler:8.6.0)
Alternatively, set android.defaultConfig.javaCompileOptions.annotationProcessorOptions.includeCompileClasspath = true to continue with previous behavior.  Note that this option is deprecated and will be removed in the future.
See https://developer.android.com/r/tools/annotation-processor-error-message.html for more details.
```
> Update build plugin to 3.0.1

- analytics-samples/analytics-sample/build.gradle
- analytics-samples/analytics-wear-sample/build.gradle
- analytics-tests/build.gradle
- analytics-wear/build.gradle
- analytics/build.gradle
Ref: https://segment.atlassian.net/browse/LIB-190
As noted in LIB-90, this fixes warnings like:
```
Configuration 'compile' in project ':analytics' is deprecated. Use 'implementation' instead.
Configuration 'testCompile' in project ':analytics' is deprecated. Use 'testImplementation' instead.
The ConfigurableReport.setDestination(Object) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use the method ConfigurableReport.setDestination(File) instead.
```
General rule here was:
* testCompile -> testImplementation since tests are not exported
* compile -> api in library since they are exported
* compile -> implementation in apps since they are not exported
> Use new dependency configurations.

- analytics/build.gradle
Ref: https://segment.atlassian.net/browse/LIB-191
Fixes the warnings:
```
> Task :analytics:lint
Ran lint on variant release: 2 issues found
Ran lint on variant debug: 2 issues found
/Users/prateek/dev/src/github.com/segmentio/analytics-android/analytics/build.gradle:16: Warning: A newer version of org.assertj:assertj-core than 1.7.1 is available: 3.8.0 [GradleDependency]
testImplementation 'org.assertj:assertj-core:1.7.1'
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/prateek/dev/src/github.com/segmentio/analytics-android/analytics/build.gradle:19: Warning: A newer version of com.squareup.okio:okio than 1.10.0 is available: 1.13.0 [GradleDependency]
testImplementation 'com.squareup.okio:okio:1.10.0'
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Explanation for issues of …
```
> Update test dependencies

- analytics-samples/analytics-sample/src/main/res/values/styles.xml
- analytics-samples/analytics-wear-sample/src/main/AndroidManifest.xml
The first one can't be fixed until ButterKnife v9 is released.
Ref: https://segment.atlassian.net/browse/LIB-192
Fixes warnings:
```
> Task :analytics-samples:analytics-sample:lint
Ran lint on variant debug: 2 issues found
Ran lint on variant release: 2 issues found
/Users/prateek/dev/src/github.com/segmentio/analytics-android/analytics-samples/analytics-sample: Warning: Lint found one or more custom checks using its older Java API; these checks are still run in compatibility mode, but this causes duplicated parsing, and in the next version lint will no longer include this legacy mode. Make sure the following lint detectors are upgraded to the new API: butterknife.lint.InvalidR2UsageDetector [ObsoleteLintCustomCheck]
Explanation for issues of type "ObsoleteLintCustomCheck":
Lint can be …
```
> Fix lint warnings.

- analytics/src/main/java/com/segment/analytics/Analytics.java
- analytics/src/main/java/com/segment/analytics/AnalyticsContext.java
- analytics/src/main/java/com/segment/analytics/Options.java
- analytics/src/main/java/com/segment/analytics/integrations/Integration.java
- gradle/gradle-mvn-push.gradle
Previously we'd get a lot of warnings like:
```
symbol:   class Nullable
location: class Analytics
/Users/prateek/dev/src/github.com/segmentio/analytics-android/analytics/src/main/java/com/segment/analytics/Analytics.java:604: error: cannot find symbol
final @NonNull String event,
^
symbol:   class NonNull
location: class Analytics
/Users/prateek/dev/src/github.com/segmentio/analytics-android/analytics/src/main/java/com/segment/analytics/Analytics.java:605: error: cannot find symbol
final @Nullable Properties properties,
^
symbol:   class Nullable
location: class Analytics
/Users/prateek/dev/src/github.com/segmentio/analytics-android/analytics/src/main/java/com/segment/analytics/Analytics.java:606: error: cannot find symbol
@Nullable final Options options) {
^
symbol:   class Nullable …
```
> Fix JavaDoc warnings

- .circleci/config.yml
- analytics-samples/analytics-sample/build.gradle
When folks don't want to set the Runscope token (e.g. contributors), we were not escaping the keys. This would cause the generated code to be invalid:
```
public static final String RUNSCOPE_TOKEN = ;
```
This causes compilation to fail with the error https://cl.ly/0Z2d101g2y0m.
To fix this, we tweak how the token is rendererd, and always wrap it with quotes. Tweaked the CI config to not wrap the token in quotes in the properties file.
Ref: LIB-221
> Fix Runscope Token escaping when not set.

- analytics/src/main/java/com/segment/analytics/Analytics.java
Previously we were setting the userId on the thread that `identify` is called (which may be any thread), but reading the userId on a background thread.
Because of this, the userId on events called before identify may have the userId from "newer" events.
```
analytics.identify("foo");
analytics.track("event"); -> may have userId foo
analytics.identify("bar");
```
To fix this, we now also set the userId on the background thread.
Originally referenced in https://github.com/segmentio/analytics-android/issues/522. Note that my original solution proposed we read the userId on the main thread to fix the issue, but the fix implemented here is to read the userId on the background thread instead.
Ref: LIB-120
Closes #522
> Set the userId on the analytics executor thread.

- analytics/src/main/java/com/segment/analytics/AnalyticsContext.java
- analytics/src/test/java/com/segment/analytics/AnalyticsContextTest.java
From https://github.com/segmentio/analytics-android/issues/481:
> The app_build_key is added to the context as an integer, as opposed to a string. This differs from OS libraries, and the general representation of context app fields as a dictionary with string values (see segment)
This is a somewhat breaking change for consumers of the field. Previously they would see a number, but now they'll see a string. Ultimately I think consistency across the libraries is better, and we'll call out this change in the changelog.
Ref: LIB-123
Closes https://github.com/segmentio/analytics-android/issues/481
> Collect `context.app.build` as a string.

- analytics/src/main/java/com/segment/analytics/SegmentIntegration.java
- analytics/src/test/java/com/segment/analytics/SegmentIntegrationTest.java
We've changed the maximum message size from to 32kb —  https://github.com/segmentio/api-validator/commit/ba561c3acc27c26ac9a55549964ffd8f17a54d6c. This is also documented at https://segment.com/docs/sources/server/http/#max-request-size.
Ref: https://segment.atlassian.net/browse/LIB-225
> Update message size limit to be 32kb.

- analytics/src/main/java/com/segment/analytics/Client.java
- analytics/src/main/java/com/segment/analytics/SegmentIntegration.java
- analytics/src/test/java/com/segment/analytics/SegmentIntegrationTest.java
As per the library guidelines, our retry policy should be:
1. Retry network errors (socket timed out, etc.)
2. Retry server errors (HTTP 5xx)
3. Do not retry client errors (HTTP 4xx)
1. Except HTTP 429.
We weren't handling the HTTP 429 case correctly. This PR updates the retry logic to correctly handle this case. This shouldn't matter too much in practice immediately because we don't serve this status code currently, but is good to have to future proof the library.
Ref: https://paper.dropbox.com/doc/Analytics-library-guidelines-2trBhLKQD4Soz4VatvuGR#:uid=189560039280582553736180&h2=Handling-Network-Errors
Ref: https://segment.atlassian.net/browse/LIB-379
> Retry HTTP 429 Errors

- analytics/src/main/java/com/segment/analytics/Analytics.java
- analytics/src/main/java/com/segment/analytics/Properties.java
- analytics/src/main/java/com/segment/analytics/Traits.java
- analytics/src/main/java/com/segment/analytics/integrations/BasePayload.java
- analytics/src/main/java/com/segment/analytics/internal/Iso8601Utils.java
These characters cause compilation to fail locally on my machine.
```
>>>  ./gradlew clean build
> Configure project :analytics
The ConfigurableReport.setDestination(Object) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use the method ConfigurableReport.setDestination(File) instead.
> Task :analytics:androidJavadocs
/Users/prateek/dev/src/github.com/segmentio/analytics-android/analytics/src/main/java/com/segment/analytics/internal/Iso8601Utils.java:26: error: unmappable character for encoding ASCII
* Jackson???s date formatter, pruned to Moshi's needs. Forked from this file:
^
/Users/prateek/dev/src/github.com/segmentio/analytics-android/analytics/src/main/java/com/segment/analytics/internal/Iso8601Utils.java:26: error: unmappable character for encoding …
```
> replace problematic characters

- analytics/src/main/java/com/segment/analytics/Analytics.java
- analytics/src/main/java/com/segment/analytics/Options.java
- analytics/src/test/java/com/segment/analytics/AnalyticsTest.java
- analytics/src/test/java/com/segment/analytics/OptionsTest.java
> Add Options#putContext method

- build.gradle
Currently fresh builds are failing with the following error:
```
A problem occurred configuring root project 'analytics-android'.
> Could not resolve all files for configuration ':classpath'.
> Could not find lint-gradle-api.jar (com.android.tools.lint:lint-gradle-api:26.1.2).
Searched in the following locations:
https://jcenter.bintray.com/com/android/tools/lint/lint-gradle-api/26.1.2/lint-gradle-api-26.1.2.jar
```
e.g. https://circleci.com/gh/segmentio/analytics-android/2896
The Gradle plugin scans all your repositories to find a dependency. However,  due to a bug in jcenter, it incorrectly signals to Gradle that it owns the dependency (even when it doesn't) and causes Gradle to stop looking further.
The fix is to move jcenter to last so that it cannot incorrectly claim the dependency …
> Fix broken build

- analytics/src/main/java/com/segment/analytics/Analytics.java
- analytics/src/main/java/com/segment/analytics/AnalyticsActivityLifecycleCallbacks.java
- analytics/src/test/java/com/segment/analytics/AnalyticsTest.java
Addresses LIB-1156 and LIB-1143.
> Add Application Open and Application Backgrounded Events

- analytics/src/main/java/com/segment/analytics/QueueFile.java
- analytics/src/test/java/com/segment/analytics/QueueFileTest.java
This will resolve an `ArrayIndexOutOfBoundsException` (#586 and #627) crash in Android 9 devices as IOExceptions are handled by `SegmentIntegration.createQueueFile`.
> Adding checks to readHeader for invalid firstOffset and lastOffset values

- analytics/src/main/java/com/segment/analytics/Crypto.java
- analytics/src/main/java/com/segment/analytics/SegmentIntegration.java
It's not currently possible to plug in a custom `Crypto` implementation for storing analytics events on disk since these abstract methods have default / package visibility.
> Make Crypto abstract methods public

- analytics/src/main/java/com/segment/analytics/Analytics.java
- analytics/src/main/java/com/segment/analytics/AnalyticsActivityLifecycleCallbacks.java
- analytics/src/test/java/com/segment/analytics/AnalyticsTest.java
**What does this PR do?**
For Application Installed, updated and first opened the build is sent as a property. This is sent as an int, although it sent as String in the Context object. Pr to standardize how this is sent.
**Any background context you want to provide?**
Previous issue for the build sent as an int in the context object: https://github.com/segmentio/analytics-android/issues/481
> Set build property to String

- build.gradle
- gradle/android.gradle
Follow up to #658.
There was an issue with running test coverage after the previous merge to master, this caused CI to fail and CI was only ran after the merge took place.
The first change is to apply the plugin on the root project, this is in the instructions for the Gradle JaCoCo plugin and is likely just a change due to the project previously using a very old version of the plugin.
Also, there was an issue with test coverage for the androidTest variant (UI tests - End-to-End tests). The issue here was that the plugin tries to generate a coverage report for 'androidTest' on the analytics module and then fails as the coverage data doesn't exist, as androidTests haven't been executed.
To fix the issue, testCoverageEnabled has been disabled, which means test coverage is produced for unit …
> Test coverage fix after previous merge to master

- analytics/src/main/java/com/segment/analytics/Analytics.java
- analytics/src/main/java/com/segment/analytics/Options.java
- analytics/src/test/java/com/segment/analytics/AnalyticsTest.java
This PR prevents the global `analyticsContext` object from being modified when a user specifies additional context key-value pairs via the `Options` property.
This PR does not modify the overriding behavior of `Options` for any of the following api's
- `track(String, Properties, Options)`
- `identify(String, Traits, Options)`
- `group(String, Traits, Options)`
- `screen(String, String, Properties, Options)`
- `alias(String, Options)`
it acknowledges the behavior, and thus we expose an easier way to get around it.
We now have a `analytics.getDefaultOptions()` api that provides u with a **copy** of the default options object used when initializing the global analytics. And here is a simple way of leveraging this new API
```java
Analytics.with(this)
.track(
"Button B Clicked",
null, …
```
> Prevent Global Context modification for one-time op

- analytics/src/main/java/com/segment/analytics/AnalyticsContext.java
- analytics/src/test/java/com/segment/analytics/AnalyticsContextTest.java
**What does this PR do?**
This PR adds the type to the device context (Customer.io for example requires the device type to be set [alongside the device token] in order to recognize devices). [The Segment iOS SDK is already setting the type.](https://github.com/segmentio/analytics-ios/blob/ac07c5f368743792c43f9c404f3781efcfb114f7/Analytics/Classes/Internal/SEGSegmentIntegration.m#L170)
**How should this be manually tested?**
Check in Segment’s event debugger if new events contain the `type` key within their `context/device` dictionary.
**Any background context you want to provide?**
We are developing in React Native and are using Firebase Cloud Messaging (via [React Native Firebase](https://rnfirebase.io/)). We want to use Customer.io to send out push notifications, so we are working on a …
> Add type to device context

- analytics/src/main/java/com/segment/analytics/AnalyticsActivityLifecycleCallbacks.java
- analytics/src/test/java/com/segment/analytics/AnalyticsTest.java
**What does this PR do?**
When trackdeeplinks is enabled, this can result in a null pointer exception as getData() can return null while intent does not. 
**Any background context you want to provide?**
Fix for following issue: https://github.com/segmentio/analytics-android/issues/657
> Catch null intent data

- analytics/src/main/java/com/segment/analytics/Analytics.java
- analytics/src/main/java/com/segment/analytics/integrations/BasePayload.java
- analytics/src/test/java/com/segment/analytics/AnalyticsTest.java
This PR fixes how `alias` works, and ensures that cached `userId` does not override the alias `userId` when making the call.
Resolves #633 and Closes #639 
- `alias` call when `userId` is cached via previous `identify` call
> Fix alias not overridden by cached value

- analytics/build.gradle
- analytics/src/main/java/com/segment/analytics/Analytics.java
- analytics/src/main/java/com/segment/analytics/AnalyticsActivityLifecycleCallbacks.java
- analytics/src/test/java/com/segment/analytics/AnalyticsTest.java
Use `androidx.lifecycle` methods to fire `Application Backgrounded | Application Foregrounded` track calls when `trackApplicationLifecycleEvents=true`.
This feature allows us to load Segment Analytics "lazily" via an Activity rather than via the Application and still hook into all the lifecycle methods. This is due to the fact that `AnalyticsActivityLifecycleCallbacks.onCreate` gets called even if Analytics is loaded after the `Application.onCreate`.
The Lifecycle methods are also the recommended method of determining if an application is foregrounded/backgrounded.
- `Application Backgrounded | Application Foregrounded` are sent when app starts. (Segment initialized via Application)
- `Application Backgrounded | Application Foregrounded` are sent when app starts. (Segment initialized via …
> Use AndroidX lifecycle functions for App Fore/Backgrounded

- analytics/build.gradle
- analytics/proguard-rules-lib.txt
The method `com.segment.analytics.ValueMap#createValueMap` uses reflection to create an instance of the given `Class<T>`. It expects a constructor receiving a `Map`.
Unfortunately, for some classes like `Address`, this constructor is not used anywhere else in the code so applications using Proguard or R8 to remove unused code will delete this constructor. The outcome is a runtime crash in the application.
Here's an example extracted from Firebase Crashlytics in our production application:
We could not reproduce the exact same execution path of our crash, which goes through the AppboyIntegration library. But we can manually force the crash by invoking the `getValueMap` method:
```java
Traits traits = new Traits();
traits.put("address", new ValueMap());
traits.getValueMap("address", …
```
> Fix: Proguard/R8 configuration for createValueMap

- analytics/src/main/java/com/segment/analytics/Analytics.java
There has been a case of 
```
Fatal Exception: java.lang.RuntimeException: Package manager has died
```
This is an Android API call, and doesnt seem like the cause is us misusing the API. Online forums' best guess is that it may be due to hardware/other software issue.
Since we do not control the API, best we can do is guard against the Exception from being thrown, and logging it internally rather than crashing the application.
Hard to reproduce. Plus this is mostly a guard against the exception being thrown, so no test cases required.
Closes #615
> handle RuntimeException when calling `getActivityInfo`

- analytics-samples/analytics-sample/src/main/java/com/segment/analytics/sample/SampleApp.java
- analytics/src/main/java/com/segment/analytics/Analytics.java
- analytics/src/main/java/com/segment/analytics/integrations/AliasPayload.java
- analytics/src/main/java/com/segment/analytics/integrations/BasePayload.java
- analytics/src/main/java/com/segment/analytics/integrations/GroupPayload.java
- analytics/src/main/java/com/segment/analytics/integrations/IdentifyPayload.java
- analytics/src/main/java/com/segment/analytics/integrations/ScreenPayload.java
- analytics/src/main/java/com/segment/analytics/integrations/TrackPayload.java
- analytics/src/main/java/com/segment/analytics/internal/Iso8601Utils.java
- analytics/src/main/java/com/segment/analytics/internal/NanoDate.java
- analytics/src/main/java/com/segment/analytics/internal/Utils.java
- analytics/src/test/java/com/segment/analytics/AnalyticsTest.java
- analytics/src/test/java/com/segment/analytics/internal/Iso8601UtilsTest.java
New Builder option to enable collection of Nanosecond resolution timestamps with this format `yyyy-MM-ddThh:mm:ss.fffffffffZ`.
```java
Analytics.Builder builder =
new Analytics.Builder(this, ANALYTICS_WRITE_KEY)
.experimentalNanosecondTimestamps()
```
Currently `java.util.Date` does not support resolution beyond milliseconds and `java.time.*` functions are not available for `<= API 21`. We could potentially have used [API Desugaring](https://developer.android.com/studio/releases/gradle-plugin#j8-library-desugaring), but this requires us to enable multidexing, which might not be favorable + could break current lower level API support. 
Considering all of this, I chose to implement a layer over `java.util.Date` which can hold higher resolution timestamps. 
**Note: the actual resolved value …
> Experimental Nanosecond timestamps

- analytics/src/main/java/com/segment/analytics/Analytics.java
This PR implements generation of timestamps for payloads at call site rather than asynchronously, enabling us to generate more accurate timestamps for each payload. This feels like it should be a default behaviour and is thus not behind a feature flag.
This should not have a major performance impact, since we only add the generation of a timestamp to the main thread.
> Generate timestamps at call site rather than asynchronously

- analytics/src/test/java/com/segment/analytics/BatchPayloadWriterTest.kt
- analytics/src/test/java/com/segment/analytics/CryptoTest.kt
- analytics/src/test/java/com/segment/analytics/IntegrationOperationTest.kt
- analytics/src/test/java/com/segment/analytics/LoggerTest.kt
- analytics/src/test/java/com/segment/analytics/OptionsTest.kt
- analytics/src/test/java/com/segment/analytics/StatsTest.kt
updated formatting of  @Test and @Throws annotations in several Kotlin tests to be in the correct order
> updated formatting of  @Test and @Throws annotations in tests

- README.md
- build.gradle
Leverage this change https://github.com/vanniktech/gradle-android-junit-jacoco-plugin/pull/55 to allow running robolectric tests under jacoco coverage.
Also add badges to highlight on the front page
> Enable jacoco test coverage to run for robolectric tests

- analytics/src/main/java/com/segment/analytics/Analytics.java
- analytics/src/main/java/com/segment/analytics/WebhookIntegration.kt
- gradle/gradle-mvn-push.gradle
This change adds a webhook device-mode destination. This is being added solely for debugging/observability purposes but can used for other use cases as well. 
Usage: Provide a user-defined unique destination key and a webhook url that can accept json payloads (for example: [webhook.site](https://webhook.site/))
```java
Analytics.Builder(this, WRITE_KEY)
.use(new WebhookIntegrationFactory(MY_DEST_KEY, MY_WEBHOOK_URL))
```
> add WebhookIntegration

- analytics/src/main/java/com/segment/analytics/Analytics.java
In order to refresh settings faster when debugging, we now change the mobile cache ttl to 1 minute when in debug mode.
> Enable faster project settings refresh when debugging enabled

- analytics/src/test/java/com/segment/analytics/AnalyticsTest.kt
LIBMOBILE-49: https://segment.atlassian.net/browse/LIBMOBILE-49
analytics.identify(null) throws an IllegalArgumentException so that couldn't be tested for resetting traits (there is an existing unit test for this).
analytics.identify() cannot be tested since the command requires at least one parameter.
analytics.identify("userId") will not have null traits since userId is a trait.
Test identifyNullTraits makes sure that when a userId is given, other traits aren't set (tested with username)
Test identifySavesPreviousTraits makes sure that when traits are defined under a userId they carry over when an identify call with only that userId is given.
> additional identify tests for LIBMOBILE-49

- analytics-samples/analytics-sample/src/main/java/com/segment/analytics/sample/SampleApp.java
- analytics/src/main/java/com/segment/analytics/Analytics.java
- analytics/src/main/java/com/segment/analytics/AnalyticsActivityLifecycleCallbacks.java
- analytics/src/test/java/com/segment/analytics/AnalyticsTest.kt
Updated from #684 
This is a potential fix for issue currently faced by some android tv users.
This change doesnt completely remove the new lifecycle process, but rather allows switching between the new and legacy flow.
A new builder option useNewLifecycleMethods is introduced which defaults to true, and to opt-out of the new flow use
```java
Analytics.Builder builder =
new Analytics.Builder(this, ANALYTICS_WRITE_KEY)
...
.experimentalUseNewLifecycleMethods(false)
```
Implementation:
This code path controls the use of the new lifecycle flow: https://github.com/segmentio/analytics-android/pull/681/files#diff-a18a86eda368939313a371b220e906f0R331
If we circumvent ^ registration, then the onStart, onCreate, onStop functions in AnalyticsActivityLifecycleCallbacks wont get implicitly called, so …
> Make new lifecycle methods opt-out

- analytics/src/main/java/com/segment/analytics/Analytics.java
- analytics/src/main/java/com/segment/analytics/internal/Utils.java
introduced NonNull annotations to prevent passing null params and throwing from constructor for those cases, also applicationContext can not be null if context is not null, updated javadoc
> minimise throwing in Analytics.Builder() constructor

- analytics/src/main/java/com/segment/analytics/Analytics.java
- analytics/src/main/java/com/segment/analytics/internal/Utils.java
- analytics/src/test/java/com/segment/analytics/AnalyticsBuilderTest.kt
Since #750 added `@NotNull` to write-key params, we can remove tests that test those edge cases.
> Remove irrelevant tests for null write-keys

- analytics/src/main/java/com/segment/analytics/Cartographer.java
- analytics/src/test/java/com/segment/analytics/CartographerTest.kt
NaN vales are being added to our JSON payload resulting in the entire payload failing. Check for these vales and now set to zero.
> Check Double NaN and Infinity Values

- analytics/src/main/java/com/segment/analytics/Cartographer.java
- analytics/src/test/java/com/segment/analytics/CartographerTest.kt
Hi! I saw the [fix for NaN](https://github.com/segmentio/analytics-android/pull/752) values in the latest release. Thanks!
I checked the changes and saw the fix is implemented for Double only. We actually had this problem with Floats, so I tried it and Segment is still parsing them as NaN.
I replicated the fix for Doubles, and decided to send you a PR with it. I hope it helps!
> Check Float NaN and Infinity

- analytics/src/main/java/com/segment/analytics/Analytics.java
- analytics/src/main/java/com/segment/analytics/integrations/BasePayload.java
As demonstrated in #757, timestamps are being reported incorrectly due to clock issues stemming from using `System.nanoTime()`. We are currently investigating on how to improve our nanosecond reporting, but since the issue is affecting the non-experimental features, this quick fix should hopefully put our regular SDK users back on track. 
_Note: Any continuing users of the `experimentalNanosecondTimestamps()` feature will still face the issue referenced in #757_
> Fix Incorrect Timestamps

- analytics/src/main/java/com/segment/analytics/Properties.java
- analytics/src/test/java/com/segment/analytics/PropertiesTest.kt
As per below we do not check to see if a `product_id` is present and only map for `id`
https://github.com/segmentio/analytics-android/issues/746
> Map product_id for a Product

- analytics/src/main/java/com/segment/analytics/AnalyticsActivityLifecycleCallbacks.java
- analytics/src/test/java/com/segment/analytics/AnalyticsTest.kt
as per #736, when tracking deep links with a bad URI it causes the app to crash. The error stems from android being able to accept a non-hierarchal URI for opening the app, but unable to parse the info using `getQueryParameterNames()`(eg of bad uri: `wc:f94d4c5b-a28e-a516-4fd7-2bf37eca3a9e@1bridge=https%3A%2F%2Fbridge.walletconnect.org&key=ccaac40bbc0b9bd17d6ee8ff58f3ccfe3e`)
This change will make it so that we do not crash the app, while tracking the deep link, but not parse any of the URI details
Closes #736
> Safely handle bad URIs when tracking deep links

- analytics/src/main/java/com/segment/analytics/AnalyticsActivityLifecycleCallbacks.java
- analytics/src/main/java/com/segment/analytics/internal/Utils.java
- analytics/src/test/java/com/segment/analytics/AnalyticsTest.kt
Following this tutorial https://clmirror.storage.googleapis.com/codelabs/deeplink-referrer/index.html?index=..%2F..index#5, we now have the ability to track the referrer for the `Deep Link Opened` event. This value can be either the website url or the app package name that contained the deep link.
> Add referrer property when tracking Deep Link Opened

- .circleci/config.yml
- analytics-samples/analytics-sample/src/main/java/com/segment/analytics/sample/SampleApp.java
- analytics/src/main/java/com/segment/analytics/AnalyticsContext.java
- analytics/src/main/java/com/segment/analytics/internal/Utils.java
- analytics/src/test/java/com/segment/analytics/AnalyticsContextTest.kt
- gradle.properties
* address violation of retrieving unsettable device
* fix unit test
> address violation of retrieving unsettable device

- analytics/build.gradle
- build.gradle
* remove jcenter and bintry, since they are shutting down on 2/1/2022
> remove jcenter and bintray

- analytics/src/main/java/com/segment/analytics/Analytics.java
- analytics/src/main/java/com/segment/analytics/AnalyticsContext.java
- analytics/src/main/java/com/segment/analytics/GetDeviceIdTask.java
- analytics/src/main/java/com/segment/analytics/internal/Utils.java
- analytics/src/test/java/com/segment/analytics/AnalyticsContextTest.kt
* fix ANR issue caused by MediaDRM api
> fix ANR issue caused by MediaDRM api

- CHANGELOG.md
- gradle.properties
* [New](https://github.com/segmentio/analytics-android/pull/817): move writeKey from http request header to payload body
> release 4.11.0

- analytics/src/main/java/com/segment/analytics/AnalyticsContext.java
fixed the issue mentioned in #726. use the implementation proposed [here](https://github.com/segmentio/analytics-android/issues/726#issuecomment-730482599).
> fix WindowManager crash on android 11+

- analytics/src/main/java/com/segment/analytics/AnalyticsContext.java
* fix the crash reported in #835
> fix DisplayMetrics crashes on android 11+
